//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kiosc_Prototype.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class data
    {
        public System.DateTime time { get; set; }
        public Nullable<int> EnergyGenearated { get; set; }
        public Nullable<int> EnergyConsumed { get; set; }
        public Nullable<int> Temperature { get; set; }
        public Nullable<int> Gas { get; set; }
    }
}
